## Run nginx using:
#     nginx -p $PWD -e stderr -c nginx.conf
## Run gunicorn as
# gunicorn -b "localhost:5000" "vox:create_app()"

daemon off;
events {}

pid nginx.pid;

http {
    access_log /dev/stdout;
    # error_log stderr debug;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        server_name localhost;
        listen 127.0.0.1:8080;
        location /voxpopulli/api/ {
            proxy_pass http://unix:./vox.sock:/api/;
        }
        location /voxpopulli/ {
            alias ./frontend/;
            index polls.html;
            try_files $uri $uri.html $uri/ =404;
        }
    }
}
