## Run nginx using:
#     nginx -p $PWD -e stderr -c nginx.conf
## Run gunicorn as
# gunicorn -b "localhost:5000" "vox:create_app()"

daemon off;
events {}

pid nginx.pid;

http {
    access_log /dev/stdout;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        server_name localhost;
        listen 127.0.0.1:8080;
        location /api/ {
            proxy_pass http://127.0.0.1:5000;
        }
        location / {
            root ./frontend;
            autoindex on;
        }
        location /poll {
            root ./frontend;
            try_files $uri /poll.html;
        }
    }
}
